name: atacem
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - anyio=3.5.0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0
  - attrs=21.4.0=pyhd3eb1b0_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1
  - bleach=4.1.0=pyhd3eb1b0_0
  - brotlipy=0.7.0
  - ca-certificates=2024.8.30
  - certifi=2024.8.30=pyhd8ed1ab_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - cryptography=37.0.1
  - debugpy=1.5.1
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4
  - idna=3.3=pyhd3eb1b0_0
  - importlib-metadata=4.11.3
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - ipykernel=6.9.1
  - ipython=7.31.1
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.1
  - jinja2=3.0.3=pyhd3eb1b0_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.4.0
  - jupyter_client=7.2.2
  - jupyter_core=4.10.0
  - jupyter_server=1.17.1
  - jupyterlab=3.3.2=pyhd3eb1b0_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.12.0
  - libsodium=1.0.18
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4
  - nbclassic=0.3.5=pyhd3eb1b0_0
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.3.0
  - nest-asyncio=1.5.5
  - nodejs=22.9.0
  - notebook=6.4.11
  - packaging=21.3=pyhd3eb1b0_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.2.4
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.8
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.15.1=pyhd3eb1b0_0
  - pytz=2022.1
  - pyzmq=22.3.0
  - requests=2.27.1=pyhd3eb1b0_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=61.2.0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.2.0
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - terminado=0.13.1
  - testpath=0.6.0
  - tornado=6.1
  - traitlets=5.1.1=pyhd3eb1b0_0
  - urllib3=1.26.9
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.37.1=pyhd3eb1b0_0
  - zeromq=4.3.4
  - zipp=3.8.0
  - pip:
      - appdirs==1.4.4
      - awscli==1.31.13
      - backports-zoneinfo==0.2.1
      - biomart==0.9.2
      - bioservices==1.11.2
      - biothings-client==0.3.1
      - botocore==1.33.13
      - cattrs==23.1.2
      - cffi==1.15.1
      - colorlog==6.9.0
      - comm==0.1.4
      - connected-components-3d==3.12.3
      - cycler==0.11.0
      - dijkstra3d==1.13.0
      - docutils==0.16
      - easydev==0.12.1
      - et-xmlfile==1.1.0
      - exceptiongroup==1.2.2
      - fonttools==4.38.0
      - future==1.0.0
      - gprofiler-official==0.3.5
      - greenlet==3.1.1
      - grequests==0.7.0
      - imageio==2.31.1
      - ipywidgets==8.1.5
      - jmespath==1.0.1
      - joblib==1.3.1
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.4
      - llvmlite==0.39.1
      - lxml==5.3.0
      - matplotlib==3.5.3
      - mpmath==1.3.0
      - mygene==3.2.2
      - networkx==2.6.3
      - npm==0.1.1
      - numba==0.56.4
      - numpy==1.21.6
      - opencv-python==4.8.1.78
      - openpyxl==3.1.2
      - optional-django==0.1.0
      - pandas==1.3.5
      - patsy==0.5.6
      - pexpect==4.9.0
      - pillow==9.5.0
      - platformdirs==4.0.0
      - ptyprocess==0.7.0
      - pyasn1==0.5.1
      - pybiomart==0.2.0
      - pywavelets==1.3.0
      - pyyaml==6.0.1
      - requests-cache==1.1.1
      - rsa==4.7.2
      - s3transfer==0.8.2
      - scikit-image==0.19.3
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - statsmodels==0.13.5
      - style==1.1.0
      - suds-community==1.2.0
      - sympy==1.10.1
      - threadpoolctl==3.1.0
      - tifffile==2021.11.2
      - tqdm==4.66.6
      - typing-extensions==4.7.1
      - tzdata==2024.2
      - tzlocal==5.1
      - update==0.0.1
      - url-normalize==1.4.3
      - widgetsnbextension==4.0.13
      - wrapt==1.16.0
      - xmltodict==0.14.2
      - zope-event==5.0
      - zope-interface==6.4.post2
