#!/bin/bash

#SBATCH --job-name=Load_Polymer      ## job name
#SBATCH -A ACCOUNT_NAME     ## account to charge
#SBATCH -p PARTITION          ## partition/queue name
#SBATCH --nodes=1            ## (-N) number of nodes to use
#SBATCH --ntasks=3           ## (-n) number of tasks to launch (1 for null sweep)
#SBATCH --cpus-per-task=1    ## number of cores the job needs

source ~/.bashrc

conda activate CONDA_ENV

##CXCL9

srun --ntasks=1 --exclusive -c 1 python LoadPolymer.py --mode ATAC --output_dir "../data" --seurat_file "../data/expression_data.xlsx" --biomart_file "../data/biomart_ensembl_ID_table_hg19.xlsx" --nucleoatacr_path "../data/Processed_NucleoATACR" --exp_name "unstim" --i_gene 2 --gene_name "CXCL9" --half_wrap 73 &

srun --ntasks=1 --exclusive -c 1 python LoadPolymer.py --mode ATAC --output_dir "../data" --seurat_file "../data/expression_data.xlsx" --biomart_file "../data/biomart_ensembl_ID_table_hg19.xlsx" --nucleoatacr_path "../data/Processed_NucleoATACR" --exp_name "lps_1h" --i_gene 2 --gene_name "CXCL9" --half_wrap 73 &

##Null Sweep

srun --ntasks=1 --exclusive -c 1 python LoadPolymer.py --mode ATAC --output_dir "../data" --seurat_file "../data/expression_data.xlsx" --biomart_file "../data/biomart_ensembl_ID_table_hg19.xlsx" --nucleoatacr_path "../data/Processed_NucleoATACR" --exp_name "NULL" --i_gene 1 --gene_name "MODEL10K" --half_wrap 73 &

wait

conda deactivate